version: "3.8"

services:
  chainlink:
    image: smartcontract/chainlink:0.9.4
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - "6688:6688"
      - "6689:6689"
    volumes:
      - ./docker_volume:/chainlink
    command: local n -p /chainlink/password -a /chainlink/api
    extra_hosts:
      # maps to ip of host (on hosts' network)
      # needs docker version >= 20.10
      # https://stackoverflow.com/questions/31324981/how-to-access-host-port-from-docker-container
      - "host.docker.internal:host-gateway"
    environment:
       - ROOT=/chainlink
       - LOG_LEVEL=debug
       # kovan
       # - ETH_CHAIN_ID=42
       # localhost dev
       - ETH_CHAIN_ID=1337
       - MIN_OUTGOING_CONFIRMATIONS=2
       - MINIMUM_CONTRACT_PAYMENT=100000000000000000
       # contract address of LINK token - kovan network
       - LINK_CONTRACT_ADDRESS=0xa36085F69e2889c224210F603D836748e7dC0088
       # contract address of LINK token - local network
       # - LINK_CONTRACT_ADDRESS=0xF4d0e956464396cEBC998F60C0AB8720161fa4c2
       - CHAINLINK_TLS_PORT=0
       - SECURE_COOKIES=false
       - GAS_UPDATER_ENABLED=true
       - ALLOW_ORIGINS="*"
       # URL of Ethereum node
       # Infura kovan
       # - ETH_URL=wss://kovan.infura.io/ws/v3/fd09fff3423341508083acb38eefb499
       # ip address of docker host
       # - ETH_URL=ws://192.168.1.109:8545
       # ip address of docker container
       # - ETH_URL=ws://172.19.0.1:8545
       # ip address of docker host - automatically mapped by docker - see 'extra_hosts'
       - ETH_URL=ws://host.docker.internal:8545
       - DATABASE_URL=postgresql://chainlink_dev:chainlink_dev@postgres:5432/chainlink_dev?sslmode=disable


  postgres:
     image: postgres:12-alpine
     restart: always
     environment:
       - POSTGRES_USER=chainlink_dev
       - POSTGRES_PASSWORD=chainlink_dev
       - POSTGRES_DB=chainlink_dev
